### PR TITLE
added details of app to the readme.md file

### LINKED ISSUE #9: Change readme
Describe our app

### PR DESCRIPTION
**Pull request by YogeshKumarSahoo**
- close #9 

check if good then merge it

### CODE REVIEW

**Comment by victorlakra14** [comment]
@YogeshKumarSahoo is it necessary to put visit tracker link in readme?

**Comment by YogeshKumarSahoo** [comment]
No

**Comment by victorlakra14** [comment]
> No

Then please remove it. I don't think it is required there. It is for our own use.

**Comment by victorlakra14** [comment]
LGTM, remove the visit tracker URL and merge.

**Review by victorlakra14 — APPROVED** [review]

**Pull request merged**
